name = "a0b_base"
description = "A0B: Base components"
version = "0.2.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "types", "builtins"]

project-files=["gnat/a0b_base.gpr"]

[configuration]
disabled = true
