name = "a0b_base"
description = "A0B: Base components"
website = "https://github.com/godunko/a0b-base"
version = "0.5.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "types", "builtins"]

project-files=["gnat/a0b_base.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.variables]
Tasking = {type = "Enum", values = ["none", "ada", "a0b"], default = "none"}
